# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  JDBC_CONNECTION: ${{ vars.JDBC_CONNECTION }}
  JDBC_USER_NAME: ${{ vars.JDBC_USER_NAME }}
  JDBC_PASSWORD: ${{ vars.JDBC_PASSWORD }}

  OKTA_ISSUER_URL: ${{ vars.OKTA_ISSUER_URL }}
  OKTA_CLIENT_ID: ${{ vars.OKTA_CLIENT_ID }}
  OKTA_CLIENT_SECRET: ${{ vars.OKTA_CLIENT_SECRET }}


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
